### ISSUE TITLE
Improve typography

### ISSUE THREAD

**Issue by alinanorakari** [Lixxia/fitbit-authenticator#1]
Hello,

I have two suggestions on how to improve the typography of the digits: groups of three and monospace numbers.

One of my favorite OTP apps on iOS https://www.hde.co.jp/otp/en/ puts the digits into groups of three, which makes it a bit easier to read and type them out. I'd like to see this in your Authenticator as well.

Monospace numbers would make the codes line up better in some of the fonts. This is just a cosmetic thing my OCD would like to have ;) https://dev.fitbit.com/build/guides/user-interface/css/#monospace-numbers Fitbit details how to access monospace numbers.

**Comment by Lixxia** [comment]
Hi,
Great idea, and thank you for the link to the monospace resource. I'll be implementing the grouping and monospace (for supported fonts) in the next version!

**Comment by Lixxia** [comment]
Both of these are now available in the latest update.
