### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by joshdinsdale** [Lixxia/fitbit-authenticator#10]
Hi, I've tried to installl using the app gallery link, but when it opens in the Fitbit app it says that there is no connection, any suggestions?

**Comment by Lixxia** [comment]
Hi! There can sometimes be connectivity issues due to Fitbit's messaging internals. Best I can advise is  attempting to restart both phone and watch. Sometimes re-opening the app on the watch can help.

Please let me know if you're able to connect!

**Comment by joshdinsdale** [comment]
Hey Thanks for getting back to me. 

I uploaded the code to fitbit studio in the end and compiled myself, which was actually pretty easy. I've only had my Ionic for about a week but am finding the whole app side of the fitbit a bit disappointing, having come from the Pebble Time Steel which was still really good. The authenticator was one of my most used Pebble apps, so I am really grateful that you have started this project!

**Comment by Lixxia** [comment]
Oh I misunderstood, thought you were running with a Versa. I currently have a beta build for the Ionic if you'd like to try that out:

https://gam.fitbit.com/gallery/app/b853f37e-1951-4720-88c3-07d1587f694d

I definitely share your misgivings (as a fellow former-pebbler) about the fitbit apps but I'm working with it best I can :D

**Comment by joshdinsdale** [comment]
I got it working on the Ionic emulator by changing adding Ionic as a build target in the project, haven't actually tried on the physical device yet, but assume it would work?
I was using an android wear device in between the Pebble and Ionic and started using [https://www.authenticatorplus.com/](url) which is pretty good, a fitbit app for that would be great!

You mention in the Readme that if the app is uninstalled, the data goes as well. Is it going to be possible to create some sort of backup do you think? I only ask as i dont really trust the performance reliability of the Fitbit app, so can see my self reinstalling it at some point and dont want to loose my code/seed data! :)

**Comment by Lixxia** [comment]
No way of storing a backup at this time. I'm wary of getting into that as there are further security considerations with downloading files from the fitbit. That's why I suggest not using this as the sole source of token generation, personally I use a mix of this and other applications to store my MFA.

**Comment by joshdinsdale** [comment]
Yeah i totally get that, i work in IT support myself so am aware of the potential risks there! :)

**Comment by Lixxia** [comment]
I've updated the main app to now be available on Ionic as well!
