### ISSUE TITLE
Not there for Ionic again.  =(

### ISSUE THREAD

**Issue by droolface** [Lixxia/fitbit-authenticator#12]
I had to restore my Ionic bc of difficulties updating to OS3 and went to reinstall authenticator and it isn’t showing up (again).  I assume this is just for the Ionic but due to the really dumb way the Fitbit app store works (hiding things) can’t really tell.  Help?

**Comment by Lixxia** [comment]
I haven't been blessed with the 3.0 update as of yet, so I can't check the store availability for Versa 3.0, but I'm still seeing it in the store for 2.2. Have you tried searching for my name (Laura) and seeing if it shows up under apps? It's not built for any specific OS version so I wouldn't expect them to suddenly drop it, but if I do see issues in the store I'll release a new build for 3.0.

**Comment by droolface** [comment]
Hi Laura - yep I tried searching every which way and no dice.  I went back and installed the beta for now.  Fitbit, compared to Pebble, is really turning out to be super disappointing.

**Comment by Lixxia** [comment]
Weird, I'll contact fitbit and see if it's not an issue on their end. The beta version and the live version I believe are currently the same, but you can try the direct link to the live version (https://gam.fitbit.com/gallery/app/ff58cce2-1f9d-4a2f-917d-3cb70c11b542) sorry I didn't think of that earlier.

I'm working on a new build that takes advantage of some 3.0 features, so maybe after that it'll pop up in the Ionic store again (if fitbit doesn't fix it first).
