### ISSUE TITLE
Amazon (or other odd length) codes get rejected

### ISSUE THREAD

**Issue by Lixxia** [Lixxia/fitbit-authenticator#3]
**Issue**
When adding an MFA key provided by Amazon, the app rejects it.

Two problems:
- Given the key length of 52 characters jsSHA's check fails and throws an error `String of HEX type must be in byte increments`
- If a user inputs the code as presented (with spaces) the app will reject it.

**Comment by Lixxia** [comment]
Solved by padding the key until it's of appropriate character length. Tested that the resulting TOTP remains unchanged. 

Added stripping of whitespace for more user-friendly entry, also some character replacements for common mixups. 

Will close when GAM update is accepted.

**Comment by lenkawamoto** [comment]
Possibly related to this bug:  I have some tokens being rejected that are 26 characters long (looks like this: aaaa bbbb cccc dddd eeee ffff gg).  I've entered and re-entered them multiple times (case sensitive, non case sensitive, with and without spaces) to be sure that I didn't typo, but they keep getting rejected by your app, while working fine on Pebble Authenticator and on Android Authenticator Plus.

UPDATE 1: This is observed using Authenticator (your app) v1.1.1

**Comment by Lixxia** [comment]
~~An update just got released today, can you let me know if you're still experiencing the issue?~~

Was able to reproduce the issue, investigating.

**Comment by Lixxia** [comment]
Hopefully I've killed this bug, the initial fix caused padding to occur when not necessary. It should now be checking against the correct value, supporting both Amazon (52 length) and 26 length codes.

This will be available in the next update. Once it's available please let me know if you are able to submit your token!

**Comment by lenkawamoto** [comment]
This issue seems resolved (at least with the 26 character long tokens) in the latest version of your app (v1.2.1).  Thanks!  ...it appears that I can't close this issue, though...

**Comment by Lixxia** [comment]
Great, thanks for reporting back! I opened it so I have to close it.
