### ISSUE TITLE
Incorrect TOTP displayed for first few seconds (on watch)

### ISSUE THREAD

**Issue by lenkawamoto** [Lixxia/fitbit-authenticator#4]
Summary:
Launching the watch app shows incorrect auth codes for the first few seconds.

Most times, only the first auth codes are incorrect and when the display (on the watch) refreshes, the auth codes are correct.  However, I've had a couple of times where I had to wait for the watch to refresh yet another time before correct auth codes were displayed.  It appears that at least the first incorrect values are always the same values (each entry has a different value, but each time I see this behaviour, each entry is showing the same incorrect value as before).  Perhaps they are calculated values using an uninitialized time value?

Environment:
* Phone is a Samsung Galaxy S6 (Verizon) running Android 7.0
* Authenticator App v1.1.1
* Watch is Fitbit Versa Special Edition
* Authenticator Plus v3.8.8 (Android Application)
* Authenticator v1.11 (Pebble Application, running on Pebble Time)

Steps to reproduce:
1. Using the Phone App, set up at least ONE valid token.
2. Launch the Watch App and observe the screen for the initial value displayed
3. Compare value with Pebble Authenticator App (or Android Authenticator Plus)
4. Exit the Watch App
5. Repeat from Step 1.

Observed Behaviour:
1. Initial value displayed does not match value displayed in Pebble Authenticator App and in Android Authenticator Plus App.
2. After a few seconds, the Versa screen refreshes and displays a new value -- this is correct and matches what is seen in Pebble Authenticator App and in Android Authenticator Plus App.
3. The initial incorrect value is consistently the SAME value on each subsequent try.

Expected Behaviour:
The Watch App never displays an incorrect code.

**Comment by Lixxia** [comment]
Thank you for the detailed report, I'll investigate this issue.

**Comment by Lixxia** [comment]
Your suspicion was correct, there was an undefined time value when the app started up.

I've added a fix for this that will be available in the next update.

**Comment by lenkawamoto** [comment]
This issue seems to be fixed with the latest version (v1.2.1).  Thanks!
