### ISSUE TITLE
Feature Request: Allow grouping by 2 or 3 when displaying TOTP codes

### ISSUE THREAD

**Issue by lenkawamoto** [Lixxia/fitbit-authenticator#6]
Allow the user to set whether the groupings for the TOTP codes are grouped by 2 or by 3.  Currently you allow for: XXX YYY, I'd like to see the option for XX YY ZZ.

**Comment by Lixxia** [comment]
I've added support for this & submitted an update to Fitbit. It should be available in the next few days!

**Comment by lenkawamoto** [comment]
Thanks for adding this feature in the latest version (v1.2.1).
