### ISSUE TITLE
Removing token from mobile app doesn't remove from watch app

### ISSUE THREAD

**Issue by lenkawamoto** [Lixxia/fitbit-authenticator#7]
Summary: Removing a token from the mobile application doesn't remove it from the watch app

I had accidentally added the same token twice (using different names) and deleted one of them from the phone application, but the watch application still shows both entries.  Subsequently, I deleted the other entry from the mobile application, but both entries are still displayed on my watch.  Out of curiosity, I then deleted a non-duplicate token that I had previously added and *IT* still displays on the watch application.

Environment:
* Phone - Samsung Galaxy S6 (Verizon) running Android 7.0
* Watch - Fitbit Versa Special Edition
* Fitbit Authenticator v1.2.1

Steps to Reproduce:
1. Launch Fitbit Authenticator on phone
2. From the settings page, add a token
3. Verify that the token is accepted and displays on the watch application
4. Close the watch application
5. Back on the phone application's settings page, delete the token
6. Relaunch the watch application and observe the displayed entries.

Observed Behaviour:
1. The newly added token is properly displayed (as expected) at Step 3.
2. Although the token is removed from the list of tokens on the phone application (Step 5), the entry is still displayed on the watch application on Step 6.

Expected Behaviour:
The removed token's calculated TOTP should not be displayed on the watch application.

**Comment by Lixxia** [comment]
Was able to reproduce, investigating.

**Comment by Lixxia** [comment]
So it seems the companion needs to be running for the deletion to go through. The companion is properly started in the event of a settings change but it seems the initial change/delete does not go through. I'll chalk this up to the flaky communication (issue known by Fitbit).

To solve this I've added a check that will see if anything was queued to be deleted while the companion was off. The item(s) should then be properly deleted once the app is started again. This fix will be released in the next update.

Thanks again for the detailed bug report!

**Comment by lenkawamoto** [comment]
This issue seems to be resolved in the latest version of your app (v1.2.2)
