### ISSUE TITLE
Make available for Fitbit Ionic also?

### ISSUE THREAD

**Issue by droolface** [Lixxia/fitbit-authenticator#9]
Hi @Lixxia would it be possible to make this app recognized as compatible with the Ionic as well as the Versa?  Not sure how much or little that entails but the Fitbit app store definitely refuses to even make this app visible for my Ionic!  Thanks

**Comment by Lixxia** [comment]
Sure I can look into this. There are some issues regarding the progress bar (I don't have an Ionic so I can't test it to ensure it draws properly), however I could work around this by disabling it for Ionic only and enforcing the text timer usage.

**Comment by droolface** [comment]
Awesome!  I'd be happy to beta test for you on my Ionic if you like.  I'm set up with FitbitOS dev access, although I haven't and prob won't realistically ever make anything with it... but I am able to use the developer bridge to side-load beta builds.  Although I'm pretty sure I remember there being emulators for seeing how things run on the device(s) -- since the Ionic came first I assume they'd have an Ionic-specific one (if I'm not totally imagining seeing them in the first place).  Anyway, let me know, and big thanks for looking into it.

**Comment by Lixxia** [comment]
I do a kind of hacky time based draw to ensure the progress bar is smoothly updated, it never seems to be quite the same in the simulator vs the actual device (I suspect due to hardware differences). We'll see how close I can get with the simulator then I may take up your offer to test :)

**Comment by droolface** [comment]
Would be my genuine honor to assist any way I can.  This app is sorely needed if there's any chance for the Ionic to ever supplant my Pebbles as my main smartwatch.

Here's my plea on Reddit which is how I found out about your app (it doesn't even show up in the FitbitOS app store at all if you're using an Ionic!): https://www.reddit.com/r/fitbit/comments/8pmqo3/if_there_are_any_fitbitos_devs_in_this_sub_id/

**Comment by droolface** [comment]
BTW - they mention one way to beta test apps here: https://gam.fitbit.com/faq

**Comment by Lixxia** [comment]
So exciting to get mentioned on reddit! Thanks for sharing the thread.

And nice find, I've been looking for something like that. I'll use that method to make a beta available once I get around to this. Thanks!

**Comment by Lixxia** [comment]
Hey there! I've created a beta build with an Ionic version.

The main thing I need tested is the outer progress bar on the device, It should take approx 30 seconds to fill the border. You can enable the text counter via settings and compare the progress bar to that. That's the only potential issue I can think of but let me know if you run into anything else!

https://gam.fitbit.com/gallery/app/b853f37e-1951-4720-88c3-07d1587f694d

**Comment by droolface** [comment]
Awesome, thanks!  Will give it a try tonight and report back.

**Comment by droolface** [comment]
Hey @Lixxia super sorry but I haven't had a chance to test it yet.  I haven't been using the Ionic lately because of some shortcomings (this will be fixing one) so I haven't had it on me.  Will get it set up and tested ASAP.

**Comment by droolface** [comment]
Hey @Lixxia OK finally had a chance to load and test the beta.  Made a little video so u can see it in vivo.  Working great except a couple minor things which I mention in the vid.  Thanks again!

https://youtu.be/1hqExxkGbdc


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Lixxia** [comment]
Fantastic, thanks so much, appreciate the effort you put into creating a video so I could see the animations/issues!

* I'll take a crack at the progress bar, but it's hard to test without access to a device given the simulator differences, so I might end up leaving it alone.
* The fractal lines on the loading circle are an issue with Fitbit's built in rotation functions, I'm gonna update it to use a new module they implemented for native spinners.
* I'll definitely center that loading screen text on Ionic, thanks for the catch.
* The one at a time token thing could be related to connectivity issues, I'll attempt to reproduce and see where I can get on that.

Thank you again for the effort, I'll make the above changes and push out a new version (probably to the main app) shortly!

**Comment by droolface** [comment]
Let me know when you update the main app and I'll test everything out again on it and let u know if all well in Ionicville.  Especially the loading multiple tokens thing.  If it's a sticky issue you could just mention it in the instructions or something... wasn't a problem once I set them up one at a time.

**Comment by Lixxia** [comment]
Hey! Couldn't reproduce the one token at a time issue, I'm inclined to think it's either Ionic-specific or a connectivity thing. I'm gonna leave the progress bar until I can think up a more elegant solution. 

The other two things I mentioned have been fixed and I've submitted a build for review in the main app. Should be available for Ionic in a few days!

**Comment by Lixxia** [comment]
Available now, let me know if you see any major issues!
